backend:
  name: github
  repo: CecileGaultier/tp-gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projets"
    label: "Projets"
    folder: "content/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "imageURL", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - label: "Tags"
        name: "tag"
        widget: "select"
        multiple: true
        options: [ "vague", "coach", "surf", "spot" ]
        default: [ "html" ]
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Like"
        name: "like"
        widget: "number"
        default: 2
        value_type: "int"
        min: 1
        max: 101
      - { label: 'Tendance', name: 'color', widget: 'color' }
      - label: "Auteur"
        name: "auteur"
        widget: "object"
        summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Public", name: "public", widget: "boolean", default: true}
          - {label: "Name", name: "name", widget: "string"}
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "DD/MM/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Street Address", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Postal Code", name: "post-code", widget: "string"}
          - label: "Image auteur"
            name: "profil"
            widget: "image"
            default: "https://cdn.pixabay.com/photo/2018/04/18/18/56/user-3331257__340.png"
            media_library:
              config:
                multiple: true

